attack_method_cls: ModelExtractionCF
attack_ml_args:
  loss: binary_crossentropy
  lr: 0.01
  metrics:
  - accuracy
cat_constraints_fn: softmax
cf_args: 
  n_steps: 200
  n_samples: 100
  step_size: 0.02
cf_method_cls: GrowingSphere
cfg_name: GrowingSphere/cancer.yaml
data: cancer
global_seed: 42
logger_type: local
n_queries: 128
save_cfg: true
detect_config:
  tau: 0.05
watermark_conifg:
  alpha: 2.5
  batch_size: 128
  eps: 0.05
  init: zeros
  k: 10
  lambdas:
  - 2.0
  - 1.0
  - 1.5
  lr: 0.02
  n_ensembels: 32
  perturb_categorical: false
  random_perturbation: false
  seed: 0
  steps: 50
  use_test_only: true
  use_vmap: true
