attack_method_cls: ModelExtractionCF
attack_ml_args:
  loss: binary_crossentropy
  lr: 0.01
  metrics:
  - accuracy
cat_constraints_fn: softmax
cf_args: {}
cf_method_cls: GrowingSphere
cfg_name: GrowingSphere/heloc.yaml
data: heloc
detect_config:
  frac: 0.2
  tau: 0.05
global_seed: 42
logger_type: local
n_queries: 128
save_cfg: true
use_default_exps: true
watermark_conifg:
  alpha: 3
  batch_size: 128
  eps: 0.05
  init: zeros
  k: 5
  lambdas:
  - 2.0
  - 1.0
  - 1.5
  lr: 0.1
  n_ensembels: 16
  perturb_categorical: false
  random_perturbation: false
  seed: 0
  steps: 50
  use_test_only: true
  use_vmap: true
