attack_method_cls: ModelExtractionCF
attack_ml_args:
  loss: binary_crossentropy
  lr: 0.01
  metrics:
  - accuracy
cat_constraints_fn: softmax
cf_args:
  max_steps: 500
  n_search_samples: 300
  step_size: 0.1
  vae_layers:
  - 20
  - 16
  - 10
  - 5
  vae_lr: 0.03
cf_method_cls: CCHVAE
cfg_name: CCHVAE/dummy.yaml
data: dummy
global_seed: 42
logger_type: local
n_queries: 128
save_cfg: true
detect_config:
  frac: 0.3
  tau: 0.1
watermark_conifg:
  alpha: 2.5
  batch_size: 64
  eps: 0.05
  init: zeros
  k: 10
  lr: 0.01
  n_ensembels: 8
  perturb_categorical: false
  random_perturbation: false
  seed: 0
  steps: 50
  use_test_only: true
  use_vmap: true
  lambdas:
  - 2.0
  - 1.5
  - 1.0
