attack_method_cls: ModelExtractionCF
attack_ml_args:
  loss: binary_crossentropy
  lr: 0.01
  metrics:
  - accuracy
cat_constraints_fn: softmax
cf_args: 
  lambda_2: 4
  lambda_3: 0
  n_cfs: 1
cf_method_cls: DiverseCF
cfg_name: DiverseCF/cancer.yaml
data: cancer
global_seed: 42
logger_type: local
n_queries: 128
save_cfg: true
detect_config:
  tau: 0.0
watermark_conifg:
  alpha: 3
  batch_size: 64
  eps: 0.1
  init: zeros
  k: 10
  lambdas:
  - 2.0
  - 1.0
  - 0.5
  lr: 0.005
  n_ensembels: 16
  perturb_categorical: false
  random_perturbation: false
  seed: 0
  steps: 50
  use_test_only: true
  use_vmap: true

