attack_method_cls: ModelExtractionCF
attack_ml_args:
  loss: binary_crossentropy
  lr: 0.01
  metrics:
  - accuracy
cat_constraints_fn: softmax
cf_args:
  lambda_2: 4
cf_method_cls: DiverseCF
cfg_name: DiverseCF/dummy.yaml
data: dummy
global_seed: 0
logger_type: local
n_queries: 128
save_cfg: true
detect_config:
  frac: 0.3
  tau: 0.05
watermark_conifg:
  alpha: 2
  batch_size: 128
  eps: 0.05
  init: zeros
  k: 10
  lr: 0.03
  n_ensembels: 8
  perturb_categorical: false
  random_perturbation: false
  seed: 0
  steps: 50
  use_test_only: true
  use_vmap: true
