attack_method_cls: ModelExtractionCF
attack_ml_args:
  loss: binary_crossentropy
  lr: 0.01
  metrics:
  - accuracy
cat_constraints_fn: softmax
cf_args:
  lambda_1: 10.0
cf_method_cls: DiverseCF
cfg_name: DiverseCF/heloc.yaml
data: heloc
detect_config:
  frac: 0.3
  tau: 0.1
global_seed: 42
logger_type: local
n_queries: 128
save_cfg: true
use_default_exps: true
watermark_conifg:
  alpha: 3
  batch_size: 64
  eps: 0.05
  init: zeros
  k: 5
  lr: 0.1
  n_ensembels: 8
  perturb_categorical: false
  random_perturbation: false
  seed: 0
  steps: 50
  use_test_only: true
  use_vmap: true
