attack_method_cls: ModelExtractionCF
attack_ml_args:
  loss: binary_crossentropy
  lr: 0.01
  metrics:
  - accuracy
cat_constraints_fn: softmax
cf_method_cls: DiverseCF
cfg_name: DiverseCF/oulad.yaml
data: oulad
global_seed: 42
logger_type: local
n_queries: 128
cf_args:
  lambda_1: 50.0
  n_steps: 2000
  lr: 0.01
save_cfg: true
detect_config:
  frac: 0.1
  tau: 0.1
watermark_conifg:
  alpha: 2
  batch_size: 64
  eps: 0.05
  init: zeros
  k: 10
  lr: 0.03
  n_ensembels: 3
  perturb_categorical: false
  random_perturbation: false
  seed: 0
  steps: 50
  use_test_only: true
  use_vmap: true
